/* ============================================================================
   AP Physics 1 — Mock Exam Question Bank
   ----------------------------------------------------------------------------
   160 multiple-choice questions (20 per unit), single correct answer.
   "answer" is the 0-based index (0-3) of the correct choice.

   Unit weights below match the OFFICIAL College Board "Course at a Glance"
   (V.1, (c) 2024, effective Fall 2024). The mock exam samples 40 questions
   using these weights so every attempt mirrors the real exam blueprint:
       U1 5 | U2 8 | U3 8 | U4 5 | U5 5 | U6 2 | U7 2 | U8 5  = 40
   ========================================================================== */

const UNITS = {
  1: { name: "Kinematics",                              official: "10–15%", examCount: 5 },
  2: { name: "Force & Translational Dynamics",          official: "18–23%", examCount: 8 },
  3: { name: "Work, Energy, & Power",                   official: "18–23%", examCount: 8 },
  4: { name: "Linear Momentum",                         official: "10–15%", examCount: 5 },
  5: { name: "Torque & Rotational Dynamics",            official: "10–15%", examCount: 5 },
  6: { name: "Energy & Momentum of Rotating Systems",   official: "5–8%",   examCount: 2 },
  7: { name: "Oscillations",                            official: "5–8%",   examCount: 2 },
  8: { name: "Fluids",                                  official: "10–15%", examCount: 5 }
};

const QUESTIONS = [
  /* ---------------------------- UNIT 1: Kinematics ---------------------------- */
  { id: "u1-01", unit: 1, topic: "Velocity vs speed", difficulty: "easy",
    question: "A jogger runs 300 m east in 100 s, then immediately runs 300 m west in 100 s, returning to the starting point. What is the jogger's average velocity for the entire 200 s trip?",
    choices: ["0 m/s", "3 m/s east", "3 m/s west", "6 m/s east"], answer: 0,
    explanation: "Average velocity = total displacement / total time. The jogger returns to the start, so displacement is 0, giving 0 m/s. (Average speed would be 600 m / 200 s = 3 m/s.)" },
  { id: "u1-02", unit: 1, topic: "Position-time graph", difficulty: "easy",
    question: "On a position-versus-time (x-t) graph, an object's line is a straight, horizontal line at x = 5 m for several seconds. What does this indicate about the object's motion?",
    choices: ["It is at rest at x = 5 m", "It moves at constant nonzero velocity", "It is accelerating uniformly", "It moves back and forth around x = 5 m"], answer: 0,
    explanation: "The slope of an x-t graph is velocity. A horizontal line has zero slope, so velocity is zero and the object is at rest." },
  { id: "u1-03", unit: 1, topic: "Free fall (time to top)", difficulty: "easy",
    question: "A ball is thrown straight up with an initial speed of 20 m/s. Using g = 10 m/s^2 and ignoring air resistance, how long does it take to reach its highest point?",
    choices: ["2 s", "4 s", "1 s", "20 s"], answer: 0,
    explanation: "At the highest point v = 0. Using v = v0 - g*t: 0 = 20 - 10*t, so t = 2 s." },
  { id: "u1-04", unit: 1, topic: "Free fall (distance)", difficulty: "easy",
    question: "An object is dropped from rest and falls freely for 3 s. Using g = 10 m/s^2 and ignoring air resistance, how far does it fall?",
    choices: ["45 m", "30 m", "90 m", "15 m"], answer: 0,
    explanation: "With v0 = 0, distance = (1/2)*g*t^2 = (1/2)(10)(9) = 45 m." },
  { id: "u1-05", unit: 1, topic: "Vector components", difficulty: "easy",
    question: "A displacement vector has components 6 m east and 8 m north. What is the magnitude of the resultant displacement?",
    choices: ["10 m", "14 m", "2 m", "48 m"], answer: 0,
    explanation: "Magnitude = sqrt(6^2 + 8^2) = sqrt(100) = 10 m (a 6-8-10 right triangle)." },
  { id: "u1-06", unit: 1, topic: "Velocity-time graph slope", difficulty: "easy",
    question: "A velocity-versus-time (v-t) graph is a straight line starting at v = 0 at t = 0 and rising steadily to v = 20 m/s at t = 5 s. What is the object's acceleration?",
    choices: ["4 m/s^2", "100 m/s^2", "0.25 m/s^2", "20 m/s^2"], answer: 0,
    explanation: "Acceleration is the slope of a v-t graph: a = (20 - 0)/(5 - 0) = 4 m/s^2." },
  { id: "u1-07", unit: 1, topic: "Projectile independence", difficulty: "easy",
    question: "From the top of a cliff, one ball is dropped from rest and, at the same instant, a second ball is launched horizontally. Ignoring air resistance, which statement is correct about when they hit the level ground below?",
    choices: ["Both balls land at the same time", "The dropped ball lands first", "The horizontally launched ball lands first", "It depends on the horizontal launch speed"], answer: 0,
    explanation: "Horizontal and vertical motions are independent. Both have the same vertical motion, so they land simultaneously." },
  { id: "u1-08", unit: 1, topic: "Kinematics (v^2 = v0^2 + 2as)", difficulty: "medium",
    question: "A cart starts from rest and accelerates uniformly at 2 m/s^2 over a distance of 25 m. What is its final speed?",
    choices: ["10 m/s", "100 m/s", "50 m/s", "5 m/s"], answer: 0,
    explanation: "v^2 = v0^2 + 2*a*s = 0 + 2(2)(25) = 100, so v = 10 m/s." },
  { id: "u1-09", unit: 1, topic: "Uniform deceleration", difficulty: "medium",
    question: "A car traveling at 30 m/s brakes uniformly and comes to a stop in 6 s. What is the car's acceleration, and how far does it travel while stopping?",
    choices: ["-5 m/s^2 and 90 m", "-5 m/s^2 and 180 m", "+5 m/s^2 and 90 m", "-6 m/s^2 and 90 m"], answer: 0,
    explanation: "a = (0 - 30)/6 = -5 m/s^2. Distance = average velocity * time = (30+0)/2 * 6 = 90 m." },
  { id: "u1-10", unit: 1, topic: "Horizontal projectile", difficulty: "medium",
    question: "A ball is launched horizontally with a speed of 15 m/s from a platform 20 m above flat ground. Using g = 10 m/s^2 and ignoring air resistance, how far horizontally from the launch point does it land?",
    choices: ["30 m", "60 m", "15 m", "45 m"], answer: 0,
    explanation: "Time to fall: 20 = (1/2)(10)*t^2, so t = 2 s. Range = (15)(2) = 30 m." },
  { id: "u1-11", unit: 1, topic: "Free fall (thrown down)", difficulty: "medium",
    question: "A stone is thrown straight down from a bridge with an initial speed of 5 m/s. Using g = 10 m/s^2 and ignoring air resistance, what is its speed after 2 s?",
    choices: ["25 m/s", "20 m/s", "15 m/s", "10 m/s"], answer: 0,
    explanation: "Taking down as positive, v = v0 + g*t = 5 + (10)(2) = 25 m/s." },
  { id: "u1-12", unit: 1, topic: "Relative velocity (river)", difficulty: "medium",
    question: "A boat heads directly across a river, pointing its bow straight toward the opposite bank with a speed of 4 m/s relative to the water. The river current flows at 3 m/s parallel to the banks. What is the boat's speed relative to the ground?",
    choices: ["5 m/s", "7 m/s", "1 m/s", "12 m/s"], answer: 0,
    explanation: "The two velocities are perpendicular: speed = sqrt(4^2 + 3^2) = 5 m/s." },
  { id: "u1-13", unit: 1, topic: "Sign of acceleration", difficulty: "medium",
    question: "An object moving in the negative x-direction has a positive acceleration. Which statement best describes its motion?",
    choices: ["It is slowing down", "It is speeding up", "It is moving at constant velocity", "It is momentarily at rest the whole time"], answer: 0,
    explanation: "When velocity (negative) and acceleration (positive) have opposite signs, the object slows down." },
  { id: "u1-14", unit: 1, topic: "Area under v-t graph", difficulty: "medium",
    question: "An object's velocity-time graph shows velocity constant at 8 m/s from t = 0 to t = 4 s, then decreasing linearly to 0 m/s from t = 4 s to t = 8 s. What total distance does the object travel?",
    choices: ["48 m", "64 m", "32 m", "40 m"], answer: 0,
    explanation: "Distance = area. Rectangle (0-4 s) = 32 m; triangle (4-8 s) = (1/2)(4)(8) = 16 m. Total = 48 m." },
  { id: "u1-15", unit: 1, topic: "Projectile velocity at top", difficulty: "medium",
    question: "A projectile is launched at an angle above the horizontal. At the highest point of its trajectory, which statement about its velocity is correct (ignoring air resistance)?",
    choices: ["Its velocity is horizontal and nonzero", "Its velocity is zero", "Its velocity is purely vertical", "Its acceleration is zero"], answer: 0,
    explanation: "At the peak the vertical velocity is zero but the horizontal component is unchanged and nonzero, so velocity is horizontal. Acceleration stays g downward." },
  { id: "u1-16", unit: 1, topic: "Angled projectile", difficulty: "hard",
    question: "A projectile is launched from level ground at 50 m/s at 37 degrees above the horizontal (sin 37 = 0.6, cos 37 = 0.8). Using g = 10 m/s^2 and ignoring air resistance, what are its maximum height and total horizontal range?",
    choices: ["Max height 45 m, range 240 m", "Max height 45 m, range 120 m", "Max height 90 m, range 240 m", "Max height 30 m, range 200 m"], answer: 0,
    explanation: "v0y = 30, v0x = 40. Max height = v0y^2/(2g) = 900/20 = 45 m. Time of flight = 2*v0y/g = 6 s. Range = 40*6 = 240 m." },
  { id: "u1-17", unit: 1, topic: "Free fall symmetry", difficulty: "hard",
    question: "A ball is thrown straight up at 30 m/s from ground level. Using g = 10 m/s^2 and ignoring air resistance, what is its velocity 2 s after launch and its height at that instant? (Take up as positive.)",
    choices: ["+10 m/s, 40 m", "-10 m/s, 40 m", "+10 m/s, 60 m", "+50 m/s, 100 m"], answer: 0,
    explanation: "v = 30 - (10)(2) = +10 m/s. Height = 30(2) - (1/2)(10)(4) = 60 - 20 = 40 m." },
  { id: "u1-18", unit: 1, topic: "Relative velocity (wind)", difficulty: "hard",
    question: "An airplane flies with an airspeed of 200 m/s pointed due north. A steady wind blows at 50 m/s due east. Which is closest to the plane's speed relative to the ground?",
    choices: ["206 m/s", "250 m/s", "150 m/s", "200 m/s"], answer: 0,
    explanation: "Perpendicular vectors: ground speed = sqrt(200^2 + 50^2) = sqrt(42500) ~ 206 m/s." },
  { id: "u1-19", unit: 1, topic: "a-t to v-t reasoning", difficulty: "hard",
    question: "An object starts from rest at t = 0. Its acceleration is +2 m/s^2 constant from t = 0 to t = 3 s, then 0 from t = 3 s to t = 6 s. What is the object's velocity at t = 6 s, and how does its position change during 3-6 s?",
    choices: ["6 m/s, position increases at a constant rate", "6 m/s, position stays constant", "0 m/s, position stays constant", "12 m/s, position increases at an increasing rate"], answer: 0,
    explanation: "From 0-3 s: v = 2(3) = 6 m/s. From 3-6 s a = 0, so v stays 6 m/s, and position increases at a constant rate." },
  { id: "u1-20", unit: 1, topic: "Two-body catch-up", difficulty: "hard",
    question: "A car passes a stationary motorcycle while traveling at a constant 20 m/s. At that instant the motorcycle starts from rest and accelerates uniformly at 4 m/s^2 in the same direction. How long after the start does the motorcycle catch up to the car?",
    choices: ["10 s", "5 s", "20 s", "8 s"], answer: 0,
    explanation: "Positions equal when 20*t = (1/2)(4)*t^2 = 2*t^2, so t = 10 s. (Both travel 200 m.)" },

  /* ----------------- UNIT 2: Force & Translational Dynamics ------------------ */
  { id: "u2-01", unit: 2, topic: "Newton's first law", difficulty: "easy",
    question: "A 1200 kg car travels in a straight line at a constant velocity of 25 m/s on a level highway. What is the net force acting on the car?",
    choices: ["0 N", "12,000 N forward", "30,000 N forward", "12,000 N backward"], answer: 0,
    explanation: "Constant velocity means zero acceleration, so the net force is 0 N. Drive force and resistive forces cancel." },
  { id: "u2-02", unit: 2, topic: "Newton's second law", difficulty: "easy",
    question: "A net force of 20 N acts on a 4 kg object on a frictionless surface. What is the magnitude of the object's acceleration?",
    choices: ["80 m/s^2", "5 m/s^2", "0.2 m/s^2", "24 m/s^2"], answer: 1,
    explanation: "a = F_net / m = 20 / 4 = 5 m/s^2." },
  { id: "u2-03", unit: 2, topic: "Weight vs mass", difficulty: "easy",
    question: "An object has a mass of 8 kg. Using g = 10 m/s^2, what is its weight on Earth?",
    choices: ["8 N", "0.8 N", "80 N", "800 N"], answer: 2,
    explanation: "Weight W = mg = 8 * 10 = 80 N." },
  { id: "u2-04", unit: 2, topic: "Newton's third law", difficulty: "easy",
    question: "A person pushes against a wall with a force of 50 N. Which statement correctly describes the third-law reaction force?",
    choices: ["The wall pushes back on the person with 50 N.", "The wall pushes back with less than 50 N because it does not move.", "There is no reaction force because the wall is stationary.", "The person pushes on the wall with an additional 50 N."], answer: 0,
    explanation: "Newton's third law: the wall pushes back on the person with exactly 50 N, regardless of motion." },
  { id: "u2-05", unit: 2, topic: "Normal force in elevator", difficulty: "medium",
    question: "A 60 kg person stands on a scale in an elevator that accelerates upward at 2 m/s^2 (g = 10 m/s^2). What is the normal force the scale reads?",
    choices: ["480 N", "600 N", "720 N", "120 N"], answer: 2,
    explanation: "N - mg = ma, so N = m(g + a) = 60(12) = 720 N (apparent weight increases)." },
  { id: "u2-06", unit: 2, topic: "Frictionless incline", difficulty: "medium",
    question: "A block is released from rest on a frictionless incline angled at 30 degrees above the horizontal (g = 10 m/s^2). What is the magnitude of its acceleration down the incline?",
    choices: ["10 m/s^2", "5 m/s^2", "8.7 m/s^2", "2.5 m/s^2"], answer: 1,
    explanation: "a = g*sin(theta) = 10*sin(30) = 5 m/s^2." },
  { id: "u2-07", unit: 2, topic: "Normal force on incline", difficulty: "medium",
    question: "A 10 kg block rests on a frictionless incline angled at 30 degrees above the horizontal (g = 10 m/s^2, cos 30 ~ 0.87). What is the magnitude of the normal force on the block?",
    choices: ["100 N", "50 N", "87 N", "115 N"], answer: 2,
    explanation: "N = mg*cos(theta) = 100 * 0.87 = 87 N (less than the full weight of 100 N)." },
  { id: "u2-08", unit: 2, topic: "Kinetic friction", difficulty: "medium",
    question: "A 5 kg box is pushed across a horizontal floor by a horizontal force of 30 N. The coefficient of kinetic friction is 0.4 (g = 10 m/s^2). What is the magnitude of the box's acceleration?",
    choices: ["6 m/s^2", "2 m/s^2", "4 m/s^2", "10 m/s^2"], answer: 1,
    explanation: "Friction f = 0.4 * 50 = 20 N. Net = 30 - 20 = 10 N. a = 10/5 = 2 m/s^2." },
  { id: "u2-09", unit: 2, topic: "Static friction", difficulty: "medium",
    question: "A 4 kg block sits on a horizontal table with a coefficient of static friction of 0.5 (g = 10 m/s^2). A horizontal force of 15 N is applied but the block does not move. What is the magnitude of the static friction force on the block?",
    choices: ["20 N", "15 N", "5 N", "0 N"], answer: 1,
    explanation: "Static friction self-adjusts up to mu_s*N = 20 N. Since 15 N < 20 N, friction equals the applied 15 N." },
  { id: "u2-10", unit: 2, topic: "Free-body diagram", difficulty: "easy",
    question: "A book slides to the right across a rough horizontal table while slowing down. Which set of forces correctly describes the free-body diagram of the book?",
    choices: ["Weight down, normal up, friction pointing left", "Weight down, normal up, friction pointing right", "Weight down, normal up, applied force right, friction left", "Only weight down and normal up"], answer: 0,
    explanation: "Gravity down, normal up, and kinetic friction opposes motion (book moves right, so friction points left). No continued applied force, so it slows." },
  { id: "u2-11", unit: 2, topic: "Atwood acceleration", difficulty: "medium",
    question: "An Atwood machine has masses of 3 kg and 2 kg connected by a light string over a frictionless, massless pulley (g = 10 m/s^2). What is the magnitude of the acceleration of the system?",
    choices: ["1 m/s^2", "2 m/s^2", "5 m/s^2", "10 m/s^2"], answer: 1,
    explanation: "a = (m1 - m2)g / (m1 + m2) = (1)(10)/5 = 2 m/s^2." },
  { id: "u2-12", unit: 2, topic: "Atwood tension", difficulty: "hard",
    question: "An Atwood machine has masses of 3 kg and 2 kg connected by a light string over a frictionless, massless pulley (g = 10 m/s^2). What is the tension in the string?",
    choices: ["50 N", "30 N", "24 N", "20 N"], answer: 2,
    explanation: "a = 2 m/s^2. For the 2 kg mass: T - m2*g = m2*a, so T = 2(10) + 2(2) = 24 N (between the two weights)." },
  { id: "u2-13", unit: 2, topic: "Blocks in contact", difficulty: "medium",
    question: "Two blocks, 2 kg and 4 kg, sit in contact on a frictionless surface. A horizontal force of 12 N is applied to the 2 kg block, pushing both. What is the magnitude of the contact force between the two blocks?",
    choices: ["12 N", "4 N", "8 N", "6 N"], answer: 2,
    explanation: "a = 12/6 = 2 m/s^2. Contact force accelerates only the 4 kg block: F = 4*2 = 8 N." },
  { id: "u2-14", unit: 2, topic: "Tension in connected blocks", difficulty: "hard",
    question: "On a frictionless horizontal surface, a 6 kg block is connected by a light string to a 2 kg block. A horizontal force of 16 N pulls the 2 kg block, dragging the 6 kg block behind it. What is the tension in the string?",
    choices: ["16 N", "12 N", "4 N", "8 N"], answer: 1,
    explanation: "a = 16/8 = 2 m/s^2. The string accelerates the 6 kg block: T = 6*2 = 12 N." },
  { id: "u2-15", unit: 2, topic: "Centripetal force", difficulty: "medium",
    question: "A 2 kg ball moves in a horizontal circle of radius 2 m at a constant speed of 4 m/s. What is the magnitude of the centripetal force on the ball?",
    choices: ["4 N", "8 N", "16 N", "32 N"], answer: 2,
    explanation: "F = m*v^2/r = 2*16/2 = 16 N, directed toward the center." },
  { id: "u2-16", unit: 2, topic: "Centripetal acceleration", difficulty: "medium",
    question: "A car rounds a flat circular curve of radius 40 m at a constant speed of 20 m/s. What is the magnitude of the car's centripetal acceleration?",
    choices: ["0.5 m/s^2", "10 m/s^2", "20 m/s^2", "40 m/s^2"], answer: 1,
    explanation: "a = v^2/r = 400/40 = 10 m/s^2, directed toward the center." },
  { id: "u2-17", unit: 2, topic: "Circular motion (crest)", difficulty: "hard",
    question: "A car drives over the top of a circular hill of radius 20 m (g = 10 m/s^2). What is the maximum speed the car can have at the top before it loses contact with the road?",
    choices: ["10 m/s", "14.1 m/s", "20 m/s", "200 m/s"], answer: 1,
    explanation: "At the top with N = 0: mg = m*v^2/r, so v = sqrt(g*r) = sqrt(200) ~ 14.1 m/s." },
  { id: "u2-18", unit: 2, topic: "Newton's gravitation", difficulty: "medium",
    question: "Two objects exert a gravitational force F on each other. If the distance between their centers is doubled while their masses stay the same, what is the new gravitational force?",
    choices: ["2F", "F/2", "F/4", "4F"], answer: 2,
    explanation: "F = G*m1*m2/r^2 (inverse-square). Doubling r gives F/4." },
  { id: "u2-19", unit: 2, topic: "Surface gravity", difficulty: "hard",
    question: "Planet X has twice the mass of Earth and twice the radius of Earth. Compared to Earth's surface gravitational field strength g, what is the surface gravitational field strength on Planet X?",
    choices: ["2g", "g", "g/2", "g/4"], answer: 2,
    explanation: "g_surface = G*M/R^2. With 2M and 2R: g_X = G(2M)/(4R^2) = (1/2)(GM/R^2) = g/2." },
  { id: "u2-20", unit: 2, topic: "Tension (elevator)", difficulty: "hard",
    question: "A 5 kg lamp hangs from the ceiling by a single vertical rope inside an elevator. The elevator accelerates downward at 4 m/s^2 (g = 10 m/s^2). What is the tension in the rope?",
    choices: ["50 N", "70 N", "30 N", "20 N"], answer: 2,
    explanation: "T - mg = ma with a = -4: T = m(g + a) = 5(6) = 30 N (less than the static 50 N)." },

  /* --------------------- UNIT 3: Work, Energy, and Power --------------------- */
  { id: "u3-01", unit: 3, topic: "Work done by a force", difficulty: "easy",
    question: "A constant horizontal force of 25 N pushes a box 4.0 m across a level floor in the same direction as the force. How much work does the force do on the box?",
    choices: ["6.25 J", "29 J", "100 J", "0 J"], answer: 2,
    explanation: "W = F*d*cos(0) = 25*4.0 = 100 J." },
  { id: "u3-02", unit: 3, topic: "Work at an angle", difficulty: "medium",
    question: "A person pulls a sled by a rope at 60 degrees above the horizontal. The tension is 50 N and the sled moves 10 m horizontally. How much work does the tension do? (cos 60 = 0.5)",
    choices: ["500 J", "250 J", "433 J", "0 J"], answer: 1,
    explanation: "W = F*d*cos(theta) = 50*10*0.5 = 250 J (only the horizontal component does work)." },
  { id: "u3-03", unit: 3, topic: "Kinetic energy", difficulty: "easy",
    question: "A 2.0 kg ball moves at 6.0 m/s. What is its kinetic energy?",
    choices: ["12 J", "24 J", "36 J", "72 J"], answer: 2,
    explanation: "KE = (1/2)mv^2 = (1/2)(2.0)(36) = 36 J." },
  { id: "u3-04", unit: 3, topic: "KE scaling", difficulty: "medium",
    question: "A car's speed doubles while its mass stays the same. By what factor does its kinetic energy change?",
    choices: ["It stays the same", "It doubles", "It quadruples", "It is cut in half"], answer: 2,
    explanation: "KE is proportional to v^2, so doubling v makes KE 4 times larger." },
  { id: "u3-05", unit: 3, topic: "Work-energy theorem", difficulty: "medium",
    question: "A 4.0 kg object initially moving at 3.0 m/s is acted on by a net force that does 32 J of work on it in the direction of motion. What is the object's final speed?",
    choices: ["5.0 m/s", "4.0 m/s", "6.4 m/s", "8.0 m/s"], answer: 0,
    explanation: "KE_i = (1/2)(4.0)(9) = 18 J. KE_f = 18 + 32 = 50 J. (1/2)(4.0)v^2 = 50, so v = 5.0 m/s." },
  { id: "u3-06", unit: 3, topic: "Work-energy (stopping)", difficulty: "medium",
    question: "A 1000 kg car moving at 20 m/s comes to rest. How much work is done by the net (braking) force on the car?",
    choices: ["+200,000 J", "-200,000 J", "-400,000 J", "-20,000 J"], answer: 1,
    explanation: "W_net = KE_f - KE_i = 0 - (1/2)(1000)(400) = -200,000 J (negative since braking opposes motion)." },
  { id: "u3-07", unit: 3, topic: "Gravitational PE", difficulty: "easy",
    question: "A 5.0 kg box is lifted 3.0 m straight up at constant speed (g = 10 m/s^2). How much gravitational potential energy does the box gain?",
    choices: ["15 J", "50 J", "150 J", "1.5 J"], answer: 2,
    explanation: "delta PE = mgh = 5.0*10*3.0 = 150 J." },
  { id: "u3-08", unit: 3, topic: "Elastic PE", difficulty: "easy",
    question: "A spring with spring constant k = 200 N/m is compressed 0.10 m. How much elastic potential energy is stored in the spring?",
    choices: ["1.0 J", "2.0 J", "10 J", "20 J"], answer: 0,
    explanation: "PE = (1/2)kx^2 = (1/2)(200)(0.01) = 1.0 J." },
  { id: "u3-09", unit: 3, topic: "Energy conservation (fall)", difficulty: "easy",
    question: "A 2.0 kg rock is dropped from rest from a height of 5.0 m. Ignoring air resistance (g = 10 m/s^2), what is its speed just before hitting the ground?",
    choices: ["5.0 m/s", "10 m/s", "50 m/s", "100 m/s"], answer: 1,
    explanation: "mgh = (1/2)mv^2, so v = sqrt(2gh) = sqrt(100) = 10 m/s (mass cancels)." },
  { id: "u3-10", unit: 3, topic: "Energy conservation (pendulum)", difficulty: "medium",
    question: "A pendulum bob is released from rest at a height of 0.20 m above its lowest point (g = 10 m/s^2, no friction). What is the speed of the bob at the lowest point?",
    choices: ["1.0 m/s", "2.0 m/s", "4.0 m/s", "0.5 m/s"], answer: 1,
    explanation: "v = sqrt(2gh) = sqrt(2*10*0.20) = sqrt(4.0) = 2.0 m/s." },
  { id: "u3-11", unit: 3, topic: "Energy conservation (incline)", difficulty: "medium",
    question: "A 1.0 kg cart starts from rest and slides down a frictionless ramp from a vertical height of 1.8 m (g = 10 m/s^2). What is its speed at the bottom?",
    choices: ["3.0 m/s", "6.0 m/s", "18 m/s", "1.8 m/s"], answer: 1,
    explanation: "Only height matters: v = sqrt(2gh) = sqrt(36) = 6.0 m/s." },
  { id: "u3-12", unit: 3, topic: "Energy with friction", difficulty: "hard",
    question: "A 2.0 kg block slides down a ramp from a height of 2.0 m and reaches the bottom moving at 4.0 m/s (g = 10 m/s^2). How much mechanical energy was lost to friction?",
    choices: ["40 J", "16 J", "24 J", "56 J"], answer: 2,
    explanation: "Initial PE = 40 J. Final KE = (1/2)(2.0)(16) = 16 J. Lost = 40 - 16 = 24 J." },
  { id: "u3-13", unit: 3, topic: "Friction work", difficulty: "hard",
    question: "A 3.0 kg box slides across a level floor and comes to rest after traveling 5.0 m. If the constant friction force is 6.0 N, what was the initial kinetic energy of the box?",
    choices: ["18 J", "30 J", "15 J", "1.2 J"], answer: 1,
    explanation: "Energy dissipated = friction * distance = 6.0 * 5.0 = 30 J, which equals the initial KE." },
  { id: "u3-14", unit: 3, topic: "Power", difficulty: "easy",
    question: "A motor does 600 J of work in 4.0 s. What is the average power output of the motor?",
    choices: ["2400 W", "150 W", "600 W", "0.0067 W"], answer: 1,
    explanation: "Power = work / time = 600 / 4.0 = 150 W." },
  { id: "u3-15", unit: 3, topic: "Power (lifting)", difficulty: "medium",
    question: "A crane lifts a 200 kg load at a constant speed of 0.50 m/s (g = 10 m/s^2). What power must the crane supply?",
    choices: ["100 W", "1000 W", "2000 W", "400 W"], answer: 1,
    explanation: "F = mg = 2000 N. Power = F*v = 2000 * 0.50 = 1000 W." },
  { id: "u3-16", unit: 3, topic: "Power vs work", difficulty: "medium",
    question: "Two identical boxes are lifted to the same height. Box X is lifted in 2.0 s and box Y in 4.0 s. Which statement is correct?",
    choices: ["The same work is done on each, but more power is used on box X", "More work is done on box X, and the power is the same", "Box Y requires more work because it takes longer", "The power is the same because the boxes are identical"], answer: 0,
    explanation: "Work = mgh is identical. Power = work/time, and X is lifted faster, so it requires more power." },
  { id: "u3-17", unit: 3, topic: "Spring launch", difficulty: "hard",
    question: "A spring with k = 800 N/m is compressed 0.20 m and used to launch a 0.50 kg ball horizontally across a frictionless surface. What is the launch speed?",
    choices: ["4.0 m/s", "8.0 m/s", "16 m/s", "32 m/s"], answer: 1,
    explanation: "(1/2)kx^2 = (1/2)(800)(0.04) = 16 J = (1/2)(0.50)v^2, so v^2 = 64, v = 8.0 m/s." },
  { id: "u3-18", unit: 3, topic: "Sign of work", difficulty: "medium",
    question: "A ball is thrown straight up. While the ball is rising, what is the sign of the work done by gravity on the ball?",
    choices: ["Positive, because gravity is a force", "Negative, because the force of gravity is opposite to the displacement", "Zero, because the ball is in the air", "Positive, because the ball will come back down"], answer: 1,
    explanation: "Displacement is up, gravity is down (theta = 180), so gravity does negative work while the ball rises." },
  { id: "u3-19", unit: 3, topic: "Spring + gravity", difficulty: "hard",
    question: "A 0.40 kg block is launched up a frictionless incline by a spring storing 8.0 J of elastic potential energy (g = 10 m/s^2). What maximum vertical height does the block rise before momentarily stopping?",
    choices: ["1.0 m", "2.0 m", "0.50 m", "4.0 m"], answer: 1,
    explanation: "Spring PE becomes gravitational PE: 8.0 = mgh = (0.40)(10)h = 4.0h, so h = 2.0 m." },
  { id: "u3-20", unit: 3, topic: "Work-energy (multiple forces)", difficulty: "hard",
    question: "A 10 kg crate is pulled 5.0 m across a level floor by a 40 N horizontal force. A friction force of 15 N opposes the motion. If the crate starts from rest, what is its final kinetic energy?",
    choices: ["200 J", "125 J", "75 J", "275 J"], answer: 1,
    explanation: "Net work = (40 - 15)(5.0) = 125 J, so KE_f = 0 + 125 = 125 J." },

  /* ------------------------- UNIT 4: Linear Momentum ------------------------- */
  { id: "u4-01", unit: 4, topic: "Momentum basics", difficulty: "easy",
    question: "A 2 kg cart moves to the right at 5 m/s. What is the magnitude of its linear momentum?",
    choices: ["2.5 kg*m/s", "7 kg*m/s", "10 kg*m/s", "25 kg*m/s"], answer: 2,
    explanation: "p = mv = 2 * 5 = 10 kg*m/s. (25 would be the kinetic energy (1/2)mv^2.)" },
  { id: "u4-02", unit: 4, topic: "Elastic collision (equal mass)", difficulty: "medium",
    question: "A 4 kg ball moving at 3 m/s collides head-on and elastically with a second 4 kg ball at rest on a frictionless surface. After the collision, what is the velocity of the second ball?",
    choices: ["0 m/s", "1.5 m/s", "3 m/s", "6 m/s"], answer: 2,
    explanation: "In a 1D elastic collision between equal masses, velocities exchange: the first ball stops and the second moves off at 3 m/s." },
  { id: "u4-03", unit: 4, topic: "Impulse-momentum theorem", difficulty: "easy",
    question: "A constant net force of 20 N acts on a 5 kg object for 3 s. What is the magnitude of the impulse delivered to the object?",
    choices: ["6 N*s", "15 N*s", "60 N*s", "100 N*s"], answer: 2,
    explanation: "Impulse J = F*t = 20 * 3 = 60 N*s (mass is not needed)." },
  { id: "u4-04", unit: 4, topic: "Impulse with rebound", difficulty: "medium",
    question: "A 0.5 kg ball traveling at 8 m/s to the right strikes a wall and rebounds at 6 m/s to the left. Taking rightward as positive, what is the impulse delivered to the ball by the wall?",
    choices: ["-7 N*s", "-1 N*s", "+1 N*s", "+7 N*s"], answer: 0,
    explanation: "J = m(v_f - v_i) = 0.5(-6 - 8) = -7 N*s (points left). Forgetting to flip the rebound sign gives +1 N*s." },
  { id: "u4-05", unit: 4, topic: "Conservation of momentum (concept)", difficulty: "easy",
    question: "Two ice skaters of different masses stand at rest facing each other on frictionless ice and push off. Which statement is correct about the instant just after they separate?",
    choices: ["They have equal speeds.", "They have equal and opposite momenta.", "They have equal kinetic energies.", "The heavier skater has greater momentum."], answer: 1,
    explanation: "Total momentum stays zero, so the two momenta are equal and opposite. The lighter skater moves faster." },
  { id: "u4-06", unit: 4, topic: "Impulse from a graph", difficulty: "medium",
    question: "A net force on a 2 kg object increases linearly from 0 N to 10 N over a time of 4 s. The object starts from rest. What is its speed at t = 4 s? (Impulse equals the area under the force-time graph.)",
    choices: ["5 m/s", "10 m/s", "20 m/s", "40 m/s"], answer: 1,
    explanation: "Impulse = (1/2)(4)(10) = 20 N*s. delta v = J/m = 20/2 = 10 m/s." },
  { id: "u4-07", unit: 4, topic: "Perfectly inelastic collision", difficulty: "medium",
    question: "A 2 kg block moving at 6 m/s slides into and sticks to a 4 kg block at rest on a frictionless surface. What is the speed of the combined blocks after the collision?",
    choices: ["1 m/s", "2 m/s", "3 m/s", "6 m/s"], answer: 1,
    explanation: "(2)(6) = (2+4)v, so v = 12/6 = 2 m/s." },
  { id: "u4-08", unit: 4, topic: "Energy loss in collision", difficulty: "hard",
    question: "A 2 kg block moving at 6 m/s slides into and sticks to a stationary 4 kg block, after which the combined blocks move at 2 m/s. How much kinetic energy is lost in the collision?",
    choices: ["0 J", "12 J", "24 J", "36 J"], answer: 2,
    explanation: "KE_i = (1/2)(2)(36) = 36 J. KE_f = (1/2)(6)(4) = 12 J. Lost = 24 J." },
  { id: "u4-09", unit: 4, topic: "Recoil", difficulty: "medium",
    question: "A 50 kg cannon, initially at rest on a frictionless surface, fires a 0.04 kg projectile horizontally at 500 m/s. What is the recoil speed of the cannon?",
    choices: ["0.4 m/s", "4 m/s", "10 m/s", "20 m/s"], answer: 0,
    explanation: "Total momentum stays zero: 50*v = 0.04*500 = 20, so v = 0.4 m/s opposite the projectile." },
  { id: "u4-10", unit: 4, topic: "Force from momentum change", difficulty: "medium",
    question: "A 1500 kg car traveling at 20 m/s is brought to rest in a collision lasting 0.5 s. What is the magnitude of the average net force on the car?",
    choices: ["750 N", "15,000 N", "30,000 N", "60,000 N"], answer: 3,
    explanation: "F = delta p / delta t = (1500)(20)/0.5 = 60,000 N." },
  { id: "u4-11", unit: 4, topic: "What is conserved", difficulty: "easy",
    question: "During a collision between two objects in an isolated system, which quantity is always conserved?",
    choices: ["Kinetic energy of each object", "Total kinetic energy of the system", "Total linear momentum of the system", "Velocity of each object"], answer: 2,
    explanation: "With no external net force, total linear momentum is always conserved. KE is conserved only in elastic collisions." },
  { id: "u4-12", unit: 4, topic: "Elastic vs inelastic", difficulty: "easy",
    question: "Which of the following is true of a perfectly inelastic collision but NOT of an elastic collision?",
    choices: ["Total momentum is conserved.", "The objects move together with a common velocity afterward.", "No external forces act during the collision.", "The total mass is conserved."], answer: 1,
    explanation: "In a perfectly inelastic collision the objects stick together and share one final velocity. Momentum and mass conservation hold for both types." },
  { id: "u4-13", unit: 4, topic: "Center of mass", difficulty: "medium",
    question: "A 2 kg point mass sits at x = 0 m and a 6 kg point mass sits at x = 8 m along a straight line. What is the x-coordinate of the center of mass?",
    choices: ["2 m", "4 m", "6 m", "8 m"], answer: 2,
    explanation: "x_cm = (2*0 + 6*8)/(2+6) = 48/8 = 6 m (closer to the heavier mass, not the midpoint)." },
  { id: "u4-14", unit: 4, topic: "Center of mass motion", difficulty: "hard",
    question: "Two objects form an isolated system on a frictionless surface. A 3 kg object moves right at 4 m/s and a 1 kg object moves left at 4 m/s. What is the velocity of the center of mass?",
    choices: ["0 m/s", "2 m/s to the right", "4 m/s to the right", "2 m/s to the left"], answer: 1,
    explanation: "v_cm = total momentum / total mass = (12 - 4)/4 = +2 m/s (to the right)." },
  { id: "u4-15", unit: 4, topic: "2D collision (concept)", difficulty: "hard",
    question: "On a frictionless surface, a 1 kg puck moving east at 3 m/s strikes a stationary 1 kg puck. After the collision, the first puck moves off at an angle north of east and the second puck moves off south of east. Which statement is correct?",
    choices: ["The total north-south component of momentum is zero.", "The total eastward component of momentum is zero.", "Each puck individually has zero north-south momentum.", "The total momentum points north."], answer: 0,
    explanation: "Initially momentum is entirely eastward (zero N-S). Momentum is conserved component-by-component, so the total N-S component stays zero." },
  { id: "u4-16", unit: 4, topic: "2D inelastic collision", difficulty: "hard",
    question: "A 2 kg object moving east at 5 m/s collides with a 3 kg object moving north at 5 m/s, and the two stick together. What is the magnitude of the total momentum after the collision?",
    choices: ["5 kg*m/s", "18 kg*m/s", "25 kg*m/s", "50 kg*m/s"], answer: 1,
    explanation: "East p = 10, north p = 15, perpendicular: total = sqrt(10^2 + 15^2) = sqrt(325) ~ 18 kg*m/s." },
  { id: "u4-17", unit: 4, topic: "Impulse and contact time", difficulty: "medium",
    question: "Two identical eggs are dropped from the same height, one onto concrete and one onto a soft pillow, and both come to rest. Compared to the egg hitting concrete, the egg hitting the pillow experiences:",
    choices: ["a smaller change in momentum", "a larger change in momentum", "the same change in momentum but a smaller average force", "the same change in momentum but a larger average force"], answer: 2,
    explanation: "Both have the same delta p. The pillow increases contact time, and F = delta p / delta t, so a longer time means a smaller average force." },
  { id: "u4-18", unit: 4, topic: "Momentum vs KE", difficulty: "hard",
    question: "Object A has mass m and speed v. Object B has mass 2m and speed v/2. How do their momenta and kinetic energies compare?",
    choices: ["Same momentum and same kinetic energy", "Same momentum, but A has greater kinetic energy", "Same kinetic energy, but A has greater momentum", "A has greater momentum and greater kinetic energy"], answer: 1,
    explanation: "p_A = mv, p_B = (2m)(v/2) = mv (equal). KE_A = (1/2)mv^2, KE_B = (1/4)mv^2, so A has twice the KE." },
  { id: "u4-19", unit: 4, topic: "Conservation (astronaut)", difficulty: "medium",
    question: "A 60 kg astronaut at rest in deep space holds a 4 kg tool. She throws the tool at 5 m/s in the +x direction. What is her resulting velocity? (Treat astronaut + tool as isolated.)",
    choices: ["0.33 m/s in +x", "0.33 m/s in -x", "5 m/s in -x", "1.25 m/s in -x"], answer: 1,
    explanation: "0 = 60*v + 4*5, so v = -20/60 = -0.33 m/s (opposite the throw)." },
  { id: "u4-20", unit: 4, topic: "Impulse with gravity", difficulty: "easy",
    question: "A 3 kg ball is dropped from rest and falls freely for 2 s. Using g = 10 m/s^2, what is the magnitude of the impulse that gravity delivers to the ball during this time?",
    choices: ["6 N*s", "15 N*s", "30 N*s", "60 N*s"], answer: 3,
    explanation: "Force = mg = 30 N, impulse = F*t = 30*2 = 60 N*s." },

  /* ------------------- UNIT 5: Torque & Rotational Dynamics ------------------- */
  { id: "u5-01", unit: 5, topic: "Angular kinematics definitions", difficulty: "easy",
    question: "A wheel starts from rest and its angular velocity increases steadily. Which quantity describes the rate at which the wheel's angular velocity changes with time?",
    choices: ["Angular displacement", "Angular acceleration", "Torque", "Rotational inertia"], answer: 1,
    explanation: "Angular acceleration (alpha) is the rate of change of angular velocity with time." },
  { id: "u5-02", unit: 5, topic: "Angular kinematics", difficulty: "easy",
    question: "A turntable starts from rest and accelerates with a constant angular acceleration of 2.0 rad/s^2. What is its angular velocity after 5.0 s?",
    choices: ["0.4 rad/s", "2.5 rad/s", "10 rad/s", "25 rad/s"], answer: 2,
    explanation: "omega = omega_0 + alpha*t = 0 + 2.0*5.0 = 10 rad/s." },
  { id: "u5-03", unit: 5, topic: "Torque (lever arm)", difficulty: "easy",
    question: "A force of 20 N is applied perpendicular to a wrench handle at a distance of 0.30 m from the bolt. What is the magnitude of the torque about the bolt?",
    choices: ["6.0 N*m", "20 N*m", "60 N*m", "0.015 N*m"], answer: 0,
    explanation: "Torque = r*F*sin(90) = 0.30*20 = 6.0 N*m." },
  { id: "u5-04", unit: 5, topic: "Torque at an angle", difficulty: "medium",
    question: "A force of 40 N is applied to the end of a 0.50 m rod at an angle of 30 degrees relative to the rod. What is the magnitude of the torque about the pivot at the other end? (sin 30 = 0.5)",
    choices: ["10 N*m", "20 N*m", "17 N*m", "40 N*m"], answer: 0,
    explanation: "Torque = r*F*sin(theta) = 0.50*40*0.5 = 10 N*m (only the perpendicular component matters)." },
  { id: "u5-05", unit: 5, topic: "Rotational inertia (scaling)", difficulty: "easy",
    question: "Two solid disks have the same mass, but disk A has twice the radius of disk B. For a disk, I = (1/2)MR^2. How does the rotational inertia of disk A compare to that of disk B?",
    choices: ["The same", "Twice as large", "Four times as large", "Half as large"], answer: 2,
    explanation: "I is proportional to R^2, so doubling R gives 4 times the rotational inertia." },
  { id: "u5-06", unit: 5, topic: "Newton's 2nd law (rotation)", difficulty: "medium",
    question: "A net torque of 12 N*m is applied to a wheel with rotational inertia 3.0 kg*m^2. What is the wheel's angular acceleration?",
    choices: ["0.25 rad/s^2", "4.0 rad/s^2", "36 rad/s^2", "9.0 rad/s^2"], answer: 1,
    explanation: "alpha = tau/I = 12/3.0 = 4.0 rad/s^2." },
  { id: "u5-07", unit: 5, topic: "Rotational equilibrium (seesaw)", difficulty: "easy",
    question: "A child of weight 300 N sits 2.0 m to the left of the pivot of a balanced, massless seesaw. A second child sits 1.5 m to the right of the pivot. What weight must the second child have to keep the seesaw balanced?",
    choices: ["225 N", "300 N", "400 N", "600 N"], answer: 2,
    explanation: "Equal torques: 300*2.0 = W*1.5, so W = 600/1.5 = 400 N." },
  { id: "u5-08", unit: 5, topic: "Angular kinematics", difficulty: "medium",
    question: "A fan blade rotating at 30 rad/s slows to a stop in 6.0 s at a constant angular acceleration. Through how many radians does it turn while stopping?",
    choices: ["5 rad", "90 rad", "180 rad", "360 rad"], answer: 1,
    explanation: "Average angular velocity = 15 rad/s, times 6.0 s = 90 rad." },
  { id: "u5-09", unit: 5, topic: "Rotational inertia (point masses)", difficulty: "medium",
    question: "Two point masses of 2.0 kg each are attached to the ends of a massless rod of total length 4.0 m. What is the rotational inertia about an axis through the center, perpendicular to the rod? (I = sum of m*r^2)",
    choices: ["4.0 kg*m^2", "8.0 kg*m^2", "16 kg*m^2", "32 kg*m^2"], answer: 2,
    explanation: "Each mass is 2.0 m from the center: I = 2*(2.0)(2.0^2) = 16 kg*m^2." },
  { id: "u5-10", unit: 5, topic: "Gravitational torque", difficulty: "medium",
    question: "A uniform horizontal beam of mass 10 kg and length 4.0 m is pivoted at its left end (g = 10 m/s^2). What is the magnitude of the gravitational torque about the pivot?",
    choices: ["100 N*m", "200 N*m", "400 N*m", "40 N*m"], answer: 1,
    explanation: "Weight (100 N) acts at the center, 2.0 m from the pivot: torque = 100*2.0 = 200 N*m." },
  { id: "u5-11", unit: 5, topic: "Newton's 2nd law (disk)", difficulty: "medium",
    question: "A solid disk of mass 4.0 kg and radius 0.50 m rotates about its central axis. A force of 8.0 N is applied tangentially at the rim. What is the angular acceleration? (For a disk, I = (1/2)MR^2.)",
    choices: ["2.0 rad/s^2", "4.0 rad/s^2", "8.0 rad/s^2", "16 rad/s^2"], answer: 2,
    explanation: "Torque = 8.0*0.50 = 4.0 N*m. I = (1/2)(4.0)(0.25) = 0.50 kg*m^2. alpha = 4.0/0.50 = 8.0 rad/s^2." },
  { id: "u5-12", unit: 5, topic: "Rotational equilibrium", difficulty: "hard",
    question: "A uniform beam of weight 200 N and length 6.0 m rests on a pivot located 2.0 m from its left end. A downward force is applied at the left end to keep the beam horizontal and in equilibrium. What is the magnitude of that force?",
    choices: ["100 N", "200 N", "300 N", "400 N"], answer: 0,
    explanation: "Weight acts at the center, 3.0 m from the left end = 1.0 m right of the pivot: torque = 200 N*m. Applied force is 2.0 m left of the pivot: F*2.0 = 200, so F = 100 N." },
  { id: "u5-13", unit: 5, topic: "Angular kinematics (omega^2)", difficulty: "hard",
    question: "A disk starts from rest and reaches an angular velocity of 12 rad/s after turning through 36 rad at constant angular acceleration. What is the angular acceleration?",
    choices: ["1.0 rad/s^2", "2.0 rad/s^2", "3.0 rad/s^2", "6.0 rad/s^2"], answer: 1,
    explanation: "omega^2 = 2*alpha*theta: 144 = 2*alpha*36 = 72*alpha, so alpha = 2.0 rad/s^2." },
  { id: "u5-14", unit: 5, topic: "Rotational inertia comparison", difficulty: "medium",
    question: "A solid sphere (I = (2/5)MR^2) and a hollow spherical shell (I = (2/3)MR^2) have the same mass and radius. The same net torque is applied to each about its center. Which has the larger angular acceleration?",
    choices: ["The solid sphere", "The hollow shell", "They have equal angular acceleration", "Cannot be determined without the radius"], answer: 0,
    explanation: "alpha = tau/I, so smaller I gives larger alpha. The solid sphere has smaller I, so larger angular acceleration." },
  { id: "u5-15", unit: 5, topic: "Torque balance", difficulty: "medium",
    question: "A massless meter stick is pivoted at the 50 cm mark. A 6.0 N weight hangs at the 20 cm mark. At what position should a 4.0 N weight be hung to balance the stick?",
    choices: ["At the 60 cm mark", "At the 70 cm mark", "At the 80 cm mark", "At the 95 cm mark"], answer: 3,
    explanation: "The 6.0 N weight is 0.30 m left of the pivot: torque = 1.8 N*m. For balance, 4.0*d = 1.8, so d = 0.45 m right of the pivot = the 95 cm mark." },
  { id: "u5-16", unit: 5, topic: "Tangential vs angular acceleration", difficulty: "hard",
    question: "A point on the rim of a wheel of radius 0.25 m has a tangential (linear) acceleration of 2.0 m/s^2 as the wheel speeds up. What is the angular acceleration of the wheel?",
    choices: ["0.5 rad/s^2", "2.0 rad/s^2", "8.0 rad/s^2", "0.125 rad/s^2"], answer: 2,
    explanation: "a = r*alpha, so alpha = a/r = 2.0/0.25 = 8.0 rad/s^2." },
  { id: "u5-17", unit: 5, topic: "Newton's 2nd law (rod)", difficulty: "hard",
    question: "A uniform rod of mass 3.0 kg and length 2.0 m is pivoted at one end, held horizontal, then released from rest. For a rod about one end, I = (1/3)ML^2. What is the initial angular acceleration just after release? (g = 10 m/s^2)",
    choices: ["5.0 rad/s^2", "7.5 rad/s^2", "10 rad/s^2", "15 rad/s^2"], answer: 1,
    explanation: "Torque = M*g*(L/2) = 3.0*10*1.0 = 30 N*m. I = (1/3)(3.0)(4.0) = 4.0 kg*m^2. alpha = 30/4.0 = 7.5 rad/s^2." },
  { id: "u5-18", unit: 5, topic: "Torque (conceptual)", difficulty: "easy",
    question: "A student wants to loosen a stubborn bolt with a wrench. Which action will produce the greatest torque on the bolt?",
    choices: ["Pushing with a small force near the bolt", "Pushing along the length of the handle toward the bolt", "Pushing perpendicular to the handle as far from the bolt as possible", "Pushing perpendicular to the handle very close to the bolt"], answer: 2,
    explanation: "Torque = r*F*sin(theta) is maximized by a large lever arm and a perpendicular force. A force along the handle gives zero torque." },
  { id: "u5-19", unit: 5, topic: "Rotational equilibrium (supports)", difficulty: "hard",
    question: "A uniform plank of weight 400 N and length 8.0 m rests horizontally on two supports, one at each end. A person of weight 600 N stands 2.0 m from the left support. What is the upward force exerted by the left support?",
    choices: ["350 N", "450 N", "550 N", "650 N"], answer: 3,
    explanation: "Torques about the right support: F_L*8.0 = 400*4.0 + 600*6.0 = 5200, so F_L = 650 N." },
  { id: "u5-20", unit: 5, topic: "v = r*omega", difficulty: "medium",
    question: "A wheel of radius 0.40 m rolls without slipping, and a point on its rim moves with a linear speed of 8.0 m/s relative to the axle. What is the angular velocity of the wheel?",
    choices: ["3.2 rad/s", "8.0 rad/s", "20 rad/s", "0.05 rad/s"], answer: 2,
    explanation: "v = r*omega, so omega = v/r = 8.0/0.40 = 20 rad/s." },

  /* ------------- UNIT 6: Energy & Momentum of Rotating Systems --------------- */
  { id: "u6-01", unit: 6, topic: "Rotational kinetic energy", difficulty: "easy",
    question: "A solid disk has a moment of inertia I = 4 kg*m^2 and rotates about its center at an angular speed of 3 rad/s. What is its rotational kinetic energy? (KE_rot = (1/2)I*omega^2)",
    choices: ["6 J", "12 J", "18 J", "36 J"], answer: 2,
    explanation: "KE_rot = (1/2)(4)(9) = 18 J." },
  { id: "u6-02", unit: 6, topic: "Angular momentum L = I*omega", difficulty: "easy",
    question: "A uniform solid disk of mass 2 kg and radius 0.5 m spins about its central axis at 4 rad/s. For a solid disk, I = (1/2)MR^2. What is the magnitude of the disk's angular momentum?",
    choices: ["0.5 kg*m^2/s", "1.0 kg*m^2/s", "2.0 kg*m^2/s", "4.0 kg*m^2/s"], answer: 1,
    explanation: "I = (1/2)(2)(0.25) = 0.25 kg*m^2. L = I*omega = 0.25*4 = 1.0 kg*m^2/s." },
  { id: "u6-03", unit: 6, topic: "Conservation of angular momentum", difficulty: "easy",
    question: "An ice skater is spinning with her arms extended. She then pulls her arms in close to her body, reducing her moment of inertia. Assuming negligible friction, what happens to her angular speed?",
    choices: ["It increases", "It decreases", "It stays the same", "It drops to zero"], answer: 0,
    explanation: "With no external torque, L = I*omega is conserved. Reducing I increases omega." },
  { id: "u6-04", unit: 6, topic: "Rolling object KE fraction", difficulty: "medium",
    question: "A solid sphere rolls without slipping along level ground. For a solid sphere, I = (2/5)MR^2. What fraction of the sphere's total kinetic energy is rotational?",
    choices: ["2/7", "1/2", "5/7", "2/5"], answer: 0,
    explanation: "KE_trans = (1/2)Mv^2, KE_rot = (1/5)Mv^2, total = (7/10)Mv^2. Fraction = (1/5)/(7/10) = 2/7." },
  { id: "u6-05", unit: 6, topic: "Angular momentum of a particle", difficulty: "easy",
    question: "A 2 kg point mass moves with speed 4 m/s along a straight line. Its line of motion passes at a perpendicular distance of 3 m from a fixed point O. What is the magnitude of its angular momentum about O? (L = m*v*r)",
    choices: ["8 kg*m^2/s", "12 kg*m^2/s", "24 kg*m^2/s", "0 kg*m^2/s"], answer: 2,
    explanation: "L = m*v*r = 2*4*3 = 24 kg*m^2/s. A particle in straight-line motion still has nonzero L about an off-line point." },
  { id: "u6-06", unit: 6, topic: "Rotational work-energy", difficulty: "medium",
    question: "A wheel with moment of inertia 5 kg*m^2 starts from rest. A constant net torque of 10 N*m acts on it as it turns through 4 rad. Using W = tau*theta = (1/2)I*omega^2, what is the final angular speed?",
    choices: ["2 rad/s", "4 rad/s", "8 rad/s", "16 rad/s"], answer: 1,
    explanation: "W = 10*4 = 40 J = (1/2)(5)omega^2, so omega^2 = 16, omega = 4 rad/s." },
  { id: "u6-07", unit: 6, topic: "Angular momentum (skater energy)", difficulty: "medium",
    question: "A spinning skater pulls in her arms so that her moment of inertia is reduced to half its original value, with no external torque. By what factor does her rotational kinetic energy change?",
    choices: ["It is halved", "It stays the same", "It doubles", "It quadruples"], answer: 2,
    explanation: "L is conserved, so halving I doubles omega. KE = (1/2)I*omega^2 doubles. The extra energy comes from the work she does pulling her arms in." },
  { id: "u6-08", unit: 6, topic: "Rotational KE comparison", difficulty: "medium",
    question: "Two flywheels have the same mass and radius but X is a uniform solid disk (I = (1/2)MR^2) and Y is a thin ring (I = MR^2). They spin at the same angular speed. How does the rotational KE of Y compare to that of X?",
    choices: ["Y has half the KE of X", "Y has the same KE as X", "Y has twice the KE of X", "Y has four times the KE of X"], answer: 2,
    explanation: "KE is proportional to I at equal omega. The ring's I is twice the disk's, so Y has twice the rotational KE." },
  { id: "u6-09", unit: 6, topic: "Angular momentum (child on disk)", difficulty: "medium",
    question: "A merry-go-round (a disk) has moment of inertia 200 kg*m^2 and rotates freely at 2 rad/s. A 50 kg child drops straight down and lands on it 2 m from the center, sticking in place. Treating the child as a point mass (I = m*r^2), what is the new angular speed?",
    choices: ["0.5 rad/s", "1.0 rad/s", "1.5 rad/s", "2.0 rad/s"], answer: 1,
    explanation: "I_child = 50*4 = 200 kg*m^2. L conserved: 200*2 = (200+200)*omega', so omega' = 400/400 = 1.0 rad/s." },
  { id: "u6-10", unit: 6, topic: "Rolling down incline", difficulty: "hard",
    question: "A uniform solid cylinder (I = (1/2)MR^2) is released from rest and rolls without slipping down an incline, descending a vertical height of 2 m (g = 10 m/s^2). Using energy conservation, what is the speed of its center of mass at the bottom?",
    choices: ["4.0 m/s", "5.2 m/s", "6.3 m/s", "8.0 m/s"], answer: 1,
    explanation: "Mgh = (3/4)Mv^2, so v = sqrt(4gh/3) = sqrt(80/3) ~ 5.2 m/s. (6.3 = sqrt(2gh) wrongly ignores rotation.)" },
  { id: "u6-11", unit: 6, topic: "Angular momentum (orbit)", difficulty: "medium",
    question: "A planet moves in an elliptical orbit around a star at one focus. As the planet moves from far from the star toward its closest approach, which statement is correct (treat the planet as a point mass)?",
    choices: ["Both angular momentum and angular speed stay constant", "Angular momentum stays constant while angular speed increases", "Angular momentum increases while angular speed stays constant", "Both angular momentum and angular speed decrease"], answer: 1,
    explanation: "Gravity is a central force (no torque about the star), so L is conserved. Since L = m*r^2*omega and r decreases, omega increases." },
  { id: "u6-12", unit: 6, topic: "Rod swing (work-energy)", difficulty: "hard",
    question: "A uniform rod of mass 3 kg and length 2 m is hinged at one end, held horizontally, then released from rest. For a rod about one end, I = (1/3)ML^2 (g = 10 m/s^2). What is the rod's angular speed when it swings to vertical? (The center of mass falls L/2.)",
    choices: ["1.7 rad/s", "3.9 rad/s", "5.5 rad/s", "7.7 rad/s"], answer: 1,
    explanation: "Mg(L/2) = (1/2)I*omega^2. I = 4 kg*m^2. 30 = 2*omega^2, so omega^2 = 15, omega ~ 3.9 rad/s." },
  { id: "u6-13", unit: 6, topic: "Total KE of rolling object", difficulty: "medium",
    question: "A solid disk (I = (1/2)MR^2) of mass 4 kg rolls without slipping with a center-of-mass speed of 3 m/s. What is its total kinetic energy?",
    choices: ["18 J", "27 J", "36 J", "54 J"], answer: 1,
    explanation: "Total KE = (3/4)Mv^2 = (3/4)(4)(9) = 27 J. (18 J is translational only.)" },
  { id: "u6-14", unit: 6, topic: "Collapsing system", difficulty: "hard",
    question: "A rotating cloud of gas collapses under gravity with no external torque. As it collapses, its radius shrinks so that its moment of inertia decreases to one quarter of its original value. By what factor does its rotational kinetic energy change?",
    choices: ["It is reduced to 1/4", "It stays the same", "It increases by a factor of 4", "It increases by a factor of 16"], answer: 2,
    explanation: "L conserved: I -> I/4 means omega -> 4*omega. KE = (1/2)I*omega^2 increases by a factor of 4 (gravity supplies the energy)." },
  { id: "u6-15", unit: 6, topic: "Stacked disks", difficulty: "medium",
    question: "A disk with moment of inertia I spins at angular speed omega. A second identical disk (same I), initially at rest, is dropped on top of it along the same axis, and the two stick together. What is the final angular speed?",
    choices: ["omega", "omega/2", "2*omega", "omega/4"], answer: 1,
    explanation: "L conserved: I*omega = 2I*omega_f, so omega_f = omega/2 (a rotational inelastic collision)." },
  { id: "u6-16", unit: 6, topic: "Hollow sphere KE fraction", difficulty: "hard",
    question: "A thin-walled hollow sphere (I = (2/3)MR^2) rolls without slipping. What fraction of its total kinetic energy is rotational?",
    choices: ["2/5", "1/2", "2/3", "3/5"], answer: 0,
    explanation: "KE_trans = (1/2)Mv^2, KE_rot = (1/3)Mv^2, total = (5/6)Mv^2. Fraction = (1/3)/(5/6) = 2/5." },
  { id: "u6-17", unit: 6, topic: "L = I*omega reasoning", difficulty: "medium",
    question: "Two objects have the same magnitude of angular momentum about a common axis. Object 1 has moment of inertia I and object 2 has moment of inertia 2I. How do their angular speeds compare?",
    choices: ["Object 2 spins twice as fast as object 1", "They spin at the same angular speed", "Object 2 spins half as fast as object 1", "Object 2 spins four times as fast as object 1"], answer: 2,
    explanation: "omega = L/I, equal L, so twice the I means half the angular speed." },
  { id: "u6-18", unit: 6, topic: "Rotational braking", difficulty: "medium",
    question: "A grinding wheel with moment of inertia 2 kg*m^2 is spinning at 10 rad/s. A constant friction torque brings it to rest after it turns through 50 rad. What is the magnitude of the friction torque? (Use W = tau*theta and the work-energy theorem.)",
    choices: ["1 N*m", "2 N*m", "4 N*m", "10 N*m"], answer: 1,
    explanation: "Initial KE = (1/2)(2)(100) = 100 J = tau*theta = tau*50, so tau = 2 N*m." },
  { id: "u6-19", unit: 6, topic: "Comparing rolling objects", difficulty: "hard",
    question: "A solid sphere (I = (2/5)MR^2) and a hollow ring (I = MR^2) are released from rest at the same height and roll without slipping down the same incline. Which reaches the bottom with the greater center-of-mass speed, and why?",
    choices: ["The sphere, because less of its energy goes into rotation", "The ring, because it has more rotational inertia to store energy", "They tie, because mass and radius cancel out", "The ring, because it has a larger angular momentum"], answer: 0,
    explanation: "v = sqrt(2gh/(1 + I/MR^2)). The sphere has the smaller I/MR^2, so it gains more translational speed." },
  { id: "u6-20", unit: 6, topic: "Child walks to center", difficulty: "hard",
    question: "A child of mass 40 kg stands at the edge of a merry-go-round of radius 2 m that is a uniform disk of moment of inertia 300 kg*m^2, rotating at 3 rad/s. The child walks to the center (r = 0). Treating the child as a point mass, what is the system's final angular speed?",
    choices: ["3 rad/s", "4.6 rad/s", "5 rad/s", "6 rad/s"], answer: 1,
    explanation: "Initial I = 300 + 40*4 = 460. Final I = 300. L conserved: 460*3 = 300*omega', so omega' = 1380/300 = 4.6 rad/s." },

  /* ---------------------------- UNIT 7: Oscillations ------------------------- */
  { id: "u7-01", unit: 7, topic: "Defining features of SHM", difficulty: "easy",
    question: "Which condition must be true for an object to undergo simple harmonic motion?",
    choices: ["The net force on the object is constant in magnitude and direction", "The net force is always directed away from the equilibrium position", "The net restoring force is proportional to the displacement and directed toward equilibrium", "The object moves with constant speed along its path"], answer: 2,
    explanation: "SHM requires a restoring force F = -kx: proportional to displacement and pointing back toward equilibrium." },
  { id: "u7-02", unit: 7, topic: "Restoring force direction", difficulty: "easy",
    question: "A block on a spring oscillates horizontally about its equilibrium position. At the instant the block is displaced to the right of equilibrium, in which direction does the net (restoring) force on the block point?",
    choices: ["To the right, in the direction of displacement", "To the left, toward equilibrium", "Zero, because the block is momentarily moving", "Upward, opposing gravity"], answer: 1,
    explanation: "The restoring force always points toward equilibrium, so when the block is right of equilibrium the force points left." },
  { id: "u7-03", unit: 7, topic: "Mass-spring period", difficulty: "easy",
    question: "A 2.0 kg block is attached to a spring of force constant k = 200 N/m and oscillates on a frictionless surface. What is the period of oscillation? (T = 2*pi*sqrt(m/k))",
    choices: ["0.10 s", "0.63 s", "1.6 s", "6.3 s"], answer: 1,
    explanation: "T = 2*pi*sqrt(2.0/200) = 2*pi*0.1 = 0.63 s." },
  { id: "u7-04", unit: 7, topic: "Pendulum period", difficulty: "easy",
    question: "A simple pendulum has a length of 2.5 m. Using g = 10 m/s^2, what is its period? (T = 2*pi*sqrt(L/g))",
    choices: ["0.50 s", "1.6 s", "3.1 s", "5.0 s"], answer: 2,
    explanation: "T = 2*pi*sqrt(2.5/10) = 2*pi*0.5 = 3.1 s." },
  { id: "u7-05", unit: 7, topic: "Pendulum independence of mass", difficulty: "easy",
    question: "Two simple pendulums have identical lengths and swing at the same small angle, but X has a 0.5 kg bob and Y has a 2.0 kg bob. How do their periods compare?",
    choices: ["X has the longer period", "Y has the longer period", "Their periods are equal", "Y's period is 4 times X's period"], answer: 2,
    explanation: "T = 2*pi*sqrt(L/g) depends only on length and g, not the bob mass, so the periods are equal." },
  { id: "u7-06", unit: 7, topic: "Position of max speed", difficulty: "easy",
    question: "A mass oscillates in SHM on a horizontal spring. At what point in the motion is the speed of the mass greatest?",
    choices: ["At the points of maximum displacement", "At the equilibrium position", "Halfway between equilibrium and maximum displacement", "The speed is the same everywhere"], answer: 1,
    explanation: "At equilibrium the restoring force is zero and all energy is kinetic, so speed is maximum there." },
  { id: "u7-07", unit: 7, topic: "Position of max acceleration", difficulty: "easy",
    question: "A block undergoes SHM on a spring with amplitude A. At which location is the magnitude of the block's acceleration greatest?",
    choices: ["At the equilibrium position", "At maximum displacement (x = +/-A)", "At x = A/2", "Acceleration is constant throughout"], answer: 1,
    explanation: "Since a = -(k/m)x, acceleration is largest where displacement is largest, at x = +/-A." },
  { id: "u7-08", unit: 7, topic: "Effect of mass on period", difficulty: "medium",
    question: "A mass on a spring oscillates with period T. If the mass is replaced by one that is 4 times larger (same spring), what is the new period?",
    choices: ["T/2", "T", "2T", "4T"], answer: 2,
    explanation: "T is proportional to sqrt(m), so multiplying m by 4 multiplies the period by 2." },
  { id: "u7-09", unit: 7, topic: "Amplitude independence", difficulty: "medium",
    question: "A block on a spring oscillates with amplitude A and period T. The block is then pulled back twice as far and released, giving amplitude 2A. Assuming the spring stays ideal, what is the new period?",
    choices: ["T/2", "T", "2T", "4T"], answer: 1,
    explanation: "For an ideal mass-spring system the period is independent of amplitude, so it remains T." },
  { id: "u7-10", unit: 7, topic: "Max speed from energy", difficulty: "medium",
    question: "A 0.50 kg block on a spring with k = 50 N/m oscillates with amplitude 0.20 m on a frictionless surface. What is the maximum speed of the block?",
    choices: ["1.0 m/s", "2.0 m/s", "4.0 m/s", "10 m/s"], answer: 1,
    explanation: "E = (1/2)kA^2 = (1/2)(50)(0.04) = 1.0 J = (1/2)(0.50)v^2, so v = 2.0 m/s." },
  { id: "u7-11", unit: 7, topic: "Frequency", difficulty: "medium",
    question: "A 2.0 kg mass on a spring with k = 200 N/m oscillates on a frictionless surface. What is the frequency of oscillation? (f = 1/T)",
    choices: ["0.63 Hz", "1.6 Hz", "3.1 Hz", "6.3 Hz"], answer: 1,
    explanation: "T = 0.63 s, so f = 1/T = 1.6 Hz." },
  { id: "u7-12", unit: 7, topic: "Changing pendulum length", difficulty: "medium",
    question: "A simple pendulum has period T. By what factor must its length be changed so that the new period is 2T?",
    choices: ["Doubled", "Quadrupled", "Halved", "Increased by a factor of sqrt(2)"], answer: 1,
    explanation: "T is proportional to sqrt(L). To double T, L must increase by a factor of 4." },
  { id: "u7-13", unit: 7, topic: "Velocity vs acceleration timing", difficulty: "medium",
    question: "A particle in SHM passes through the equilibrium position. At that instant, which statement is correct?",
    choices: ["Both velocity and acceleration are maximum", "Velocity is maximum and acceleration is zero", "Velocity is zero and acceleration is maximum", "Both velocity and acceleration are zero"], answer: 1,
    explanation: "At equilibrium x = 0, so acceleration is zero, while speed is maximum (all energy is kinetic)." },
  { id: "u7-14", unit: 7, topic: "Energy distribution", difficulty: "medium",
    question: "A block oscillates in SHM with amplitude A on a frictionless spring. At what displacement from equilibrium is the kinetic energy equal to the potential energy?",
    choices: ["x = 0", "x = A/2", "x = A/sqrt(2) (about 0.71A)", "x = A"], answer: 2,
    explanation: "PE = (1/2)kx^2 and E = (1/2)kA^2. Setting PE = E/2 gives x = A/sqrt(2)." },
  { id: "u7-15", unit: 7, topic: "Pendulum on another planet", difficulty: "hard",
    question: "A pendulum of fixed length has period 2.0 s on Earth (g = 10 m/s^2). It is taken to a planet where the gravitational field strength is 2.5 m/s^2 (one-fourth of Earth's). What is its period there?",
    choices: ["0.50 s", "1.0 s", "4.0 s", "8.0 s"], answer: 2,
    explanation: "T is proportional to 1/sqrt(g). Reducing g to one-fourth multiplies the period by 2, giving 4.0 s." },
  { id: "u7-16", unit: 7, topic: "Max velocity and acceleration", difficulty: "hard",
    question: "A 0.10 kg block on a spring with k = 40 N/m oscillates with amplitude 0.10 m. With vmax = A*sqrt(k/m) and amax = A*(k/m), what are the maximum speed and maximum acceleration?",
    choices: ["vmax = 2.0 m/s, amax = 40 m/s^2", "vmax = 0.50 m/s, amax = 20 m/s^2", "vmax = 4.0 m/s, amax = 4.0 m/s^2", "vmax = 2.0 m/s, amax = 4.0 m/s^2"], answer: 0,
    explanation: "k/m = 400, sqrt(k/m) = 20. vmax = 0.10*20 = 2.0 m/s. amax = 0.10*400 = 40 m/s^2." },
  { id: "u7-17", unit: 7, topic: "Energy and amplitude scaling", difficulty: "hard",
    question: "A mass-spring system oscillates with amplitude A and total mechanical energy E. If the amplitude is tripled to 3A (same spring and mass), what is the new total energy and the new maximum speed compared to before?",
    choices: ["Energy becomes 3E; max speed becomes 3 times as large", "Energy becomes 9E; max speed becomes 3 times as large", "Energy becomes 9E; max speed stays the same", "Energy becomes 3E; max speed becomes sqrt(3) times as large"], answer: 1,
    explanation: "E = (1/2)kA^2 is proportional to A^2, so energy becomes 9E. vmax is proportional to A, so it triples." },
  { id: "u7-18", unit: 7, topic: "Vertical spring", difficulty: "hard",
    question: "A 1.0 kg mass is hung from a vertical spring with force constant k = 50 N/m (g = 10 m/s^2) and comes to rest, then is set oscillating. By how much does the spring stretch at the new equilibrium, and what is the period of oscillation?",
    choices: ["Stretch = 0.20 m; period = 0.89 s", "Stretch = 0.20 m; period = 2.0 s", "Stretch = 0.50 m; period = 0.89 s", "Stretch = 0.10 m; period = 1.3 s"], answer: 0,
    explanation: "x = mg/k = 10/50 = 0.20 m. Period is still T = 2*pi*sqrt(m/k) = 2*pi*sqrt(0.02) = 0.89 s." },
  { id: "u7-19", unit: 7, topic: "Reading SHM equation", difficulty: "hard",
    question: "The position of an object in SHM is x = 0.050*cos(4*pi*t), where x is in meters and t in seconds. What are the amplitude and period of the motion?",
    choices: ["Amplitude 0.050 m, period 0.50 s", "Amplitude 0.050 m, period 4*pi s", "Amplitude 0.10 m, period 0.50 s", "Amplitude 0.050 m, period 2.0 s"], answer: 0,
    explanation: "Comparing to x = A*cos((2*pi/T)t): A = 0.050 m, and 2*pi/T = 4*pi gives T = 0.50 s." },
  { id: "u7-20", unit: 7, topic: "Comparing two oscillators", difficulty: "hard",
    question: "Block X (mass m, spring constant k) and block Y (mass 4m, spring constant 4k) each oscillate on frictionless surfaces. How do their periods compare?",
    choices: ["X has a longer period than Y", "Y has a longer period than X", "Their periods are equal", "Y's period is 4 times X's period"], answer: 2,
    explanation: "T = 2*pi*sqrt(m/k). For Y, sqrt(4m/4k) = sqrt(m/k), the same as X, so the periods are equal." },

  /* ------------------------------ UNIT 8: Fluids ----------------------------- */
  { id: "u8-01", unit: 8, topic: "Density", difficulty: "easy",
    question: "A solid block has a mass of 600 g and a volume of 200 cm^3. What is its density?",
    choices: ["0.33 g/cm^3", "3 g/cm^3", "120 g/cm^3", "800 g/cm^3"], answer: 1,
    explanation: "Density = mass/volume = 600/200 = 3 g/cm^3." },
  { id: "u8-02", unit: 8, topic: "Specific gravity", difficulty: "easy",
    question: "An oil has a density of 800 kg/m^3. Using rho_water = 1000 kg/m^3, what is the specific gravity of the oil?",
    choices: ["0.8", "1.25", "8.0", "800"], answer: 0,
    explanation: "Specific gravity = density / density of water = 800/1000 = 0.8 (dimensionless)." },
  { id: "u8-03", unit: 8, topic: "Pressure vs force", difficulty: "easy",
    question: "Which statement correctly distinguishes pressure from force in a fluid?",
    choices: ["Pressure is force per unit area and is a scalar; force has a direction.", "Pressure and force are the same quantity measured in newtons.", "Pressure is force times area and points downward.", "Pressure is a vector and force is a scalar."], answer: 0,
    explanation: "Pressure P = F/A is force per unit area, a scalar in pascals. Force is a vector in newtons." },
  { id: "u8-04", unit: 8, topic: "Gauge pressure with depth", difficulty: "easy",
    question: "A diver is 5 m below the surface of a freshwater lake (g = 10 m/s^2, rho = 1000 kg/m^3). What is the GAUGE pressure (due to the water alone) at this depth?",
    choices: ["5,000 Pa", "50,000 Pa", "100,000 Pa", "150,000 Pa"], answer: 1,
    explanation: "Gauge pressure = rho*g*h = 1000*10*5 = 50,000 Pa (excludes atmospheric pressure)." },
  { id: "u8-05", unit: 8, topic: "Absolute pressure", difficulty: "medium",
    question: "At the same 5 m depth in a freshwater lake, atmospheric pressure at the surface is P0 = 100,000 Pa (g = 10 m/s^2, rho = 1000 kg/m^3). What is the ABSOLUTE pressure at this depth?",
    choices: ["50,000 Pa", "100,000 Pa", "150,000 Pa", "500,000 Pa"], answer: 2,
    explanation: "P = P0 + rho*g*h = 100,000 + 50,000 = 150,000 Pa. Forgetting atmospheric pressure is a common error." },
  { id: "u8-06", unit: 8, topic: "Pressure and density", difficulty: "medium",
    question: "Two open containers sit on a table. One holds water (rho = 1000 kg/m^3) and the other an unknown liquid. At a depth of 2 m the gauge pressure in the water equals the gauge pressure in the unknown liquid at a depth of 2.5 m. What is the density of the unknown liquid? (g = 10 m/s^2)",
    choices: ["640 kg/m^3", "800 kg/m^3", "1000 kg/m^3", "1250 kg/m^3"], answer: 1,
    explanation: "rho_w*g*h_w = rho_x*g*h_x: 1000*2 = rho_x*2.5, so rho_x = 800 kg/m^3." },
  { id: "u8-07", unit: 8, topic: "Pressure depends on depth", difficulty: "medium",
    question: "Three open vessels of very different shapes (a narrow cylinder, a wide cone, and an irregular flask) are each filled with water to exactly the same height h. How does the pressure at the bottom of each vessel compare?",
    choices: ["Greatest in the vessel holding the most water.", "The same in all three, because pressure depends only on depth.", "Greatest in the narrowest vessel.", "Greatest in the widest vessel."], answer: 1,
    explanation: "Static fluid pressure depends only on depth (P = P0 + rho*g*h), not the container shape or amount of fluid." },
  { id: "u8-08", unit: 8, topic: "Pascal's principle", difficulty: "easy",
    question: "In a hydraulic lift, a force is applied to a small piston of area 0.01 m^2 and transmitted to a large piston of area 0.50 m^2. By what factor is the output force larger than the input force?",
    choices: ["50", "25", "0.02", "1"], answer: 0,
    explanation: "Equal pressure: F_out/F_in = A_out/A_in = 0.50/0.01 = 50." },
  { id: "u8-09", unit: 8, topic: "Hydraulics", difficulty: "medium",
    question: "A hydraulic press has a small piston of area 0.02 m^2 and a large piston of area 0.40 m^2. If a 100 N force is applied to the small piston, what force is exerted by the large piston?",
    choices: ["5 N", "100 N", "500 N", "2000 N"], answer: 3,
    explanation: "F_large = F_small*(A_large/A_small) = 100*(0.40/0.02) = 100*20 = 2000 N." },
  { id: "u8-10", unit: 8, topic: "Hydraulics (work)", difficulty: "hard",
    question: "In a hydraulic lift, the input piston (area A1) is pushed down 0.20 m, raising the output piston (area A2 = 10*A1). Assuming the fluid is incompressible, how far does the output piston rise, and how does the output work compare to the input work?",
    choices: ["0.02 m; output work equals input work", "0.02 m; output work is 10 times input work", "2.0 m; output work equals input work", "0.20 m; output work is 10 times input work"], answer: 0,
    explanation: "A1*d1 = A2*d2, so d2 = 0.20/10 = 0.02 m. Force x10 but distance /10, so work is conserved." },
  { id: "u8-11", unit: 8, topic: "Buoyant force", difficulty: "easy",
    question: "An object is fully submerged in water and displaces 0.002 m^3 of water (rho = 1000 kg/m^3, g = 10 m/s^2). What is the buoyant force on the object?",
    choices: ["0.02 N", "2 N", "20 N", "200 N"], answer: 2,
    explanation: "Buoyant force = rho*V*g = 1000*0.002*10 = 20 N." },
  { id: "u8-12", unit: 8, topic: "Floating fraction", difficulty: "medium",
    question: "A wooden block of density 600 kg/m^3 floats in water (rho = 1000 kg/m^3). What fraction of the block's volume is submerged below the surface?",
    choices: ["0.4", "0.6", "1.0", "1.67"], answer: 1,
    explanation: "Fraction submerged = rho_object/rho_fluid = 600/1000 = 0.6 (60% submerged)." },
  { id: "u8-13", unit: 8, topic: "Apparent weight", difficulty: "medium",
    question: "A metal block weighs 50 N in air. When fully submerged in water it displaces 0.002 m^3 (rho = 1000 kg/m^3, g = 10 m/s^2). What is the block's apparent weight while submerged?",
    choices: ["20 N", "30 N", "50 N", "70 N"], answer: 1,
    explanation: "Buoyant force = 20 N. Apparent weight = 50 - 20 = 30 N." },
  { id: "u8-14", unit: 8, topic: "Buoyancy comparison", difficulty: "hard",
    question: "Two solid balls have the SAME volume but different masses. Ball X has mass 3 kg and ball Y has mass 5 kg. Both are fully submerged and held underwater. How do the buoyant forces on them compare?",
    choices: ["The buoyant force on Y is larger because it is heavier.", "The buoyant force on X is larger because it is lighter.", "The buoyant forces are equal because they displace the same volume.", "No buoyant force acts on either since both would sink."], answer: 2,
    explanation: "Buoyant force = rho*V*g. Equal volumes displace equal water, so the buoyant forces are equal regardless of mass." },
  { id: "u8-15", unit: 8, topic: "Density from floating", difficulty: "hard",
    question: "An ice cube floats in a glass of water with exactly 90% of its volume submerged. What is the density of the ice? (rho_water = 1000 kg/m^3)",
    choices: ["111 kg/m^3", "900 kg/m^3", "1000 kg/m^3", "1111 kg/m^3"], answer: 1,
    explanation: "rho_object/rho_fluid = fraction submerged = 0.90, so rho_ice = 0.90*1000 = 900 kg/m^3." },
  { id: "u8-16", unit: 8, topic: "Continuity equation", difficulty: "easy",
    question: "Water flows through a horizontal pipe whose cross-sectional area decreases from 0.06 m^2 to 0.02 m^2. If the water speed in the wide section is 2 m/s, what is the speed in the narrow section?",
    choices: ["0.67 m/s", "2 m/s", "6 m/s", "18 m/s"], answer: 2,
    explanation: "A1*v1 = A2*v2: v2 = (0.06/0.02)*2 = 6 m/s. Fluid speeds up where the pipe narrows." },
  { id: "u8-17", unit: 8, topic: "Continuity (radius)", difficulty: "medium",
    question: "Water flows through a pipe whose radius doubles from one section to the next (narrow to wide). If the speed in the narrow section is 8 m/s, what is the speed in the wide section?",
    choices: ["32 m/s", "16 m/s", "4 m/s", "2 m/s"], answer: 3,
    explanation: "Area scales with radius^2, so doubling the radius quadruples the area. v_wide = 8*(1/4) = 2 m/s." },
  { id: "u8-18", unit: 8, topic: "Continuity (concept)", difficulty: "medium",
    question: "An incompressible fluid flows steadily through a horizontal pipe that gradually narrows. As the fluid moves into the narrower region, which statement is correct?",
    choices: ["The volume flow rate increases and the speed increases.", "The volume flow rate stays the same and the speed increases.", "The volume flow rate stays the same and the speed decreases.", "The volume flow rate decreases and the speed stays the same."], answer: 1,
    explanation: "Volume flow rate A*v is constant for steady incompressible flow, so as area decreases the speed increases." },
  { id: "u8-19", unit: 8, topic: "Bernoulli (concept)", difficulty: "hard",
    question: "Water flows through a horizontal pipe (no change in height) that narrows from a wide section to a narrow section. According to Bernoulli's principle, how does the pressure in the narrow section compare to the pressure in the wide section?",
    choices: ["Higher in the narrow section because the fluid moves faster there.", "Lower in the narrow section because the fluid moves faster there.", "The same because the pipe is horizontal.", "Lower in the narrow section because the fluid moves slower there."], answer: 1,
    explanation: "By continuity the fluid speeds up in the narrow section. For horizontal flow, P + (1/2)rho*v^2 = constant, so higher speed means lower pressure." },
  { id: "u8-20", unit: 8, topic: "Bernoulli (quantitative)", difficulty: "hard",
    question: "Water (rho = 1000 kg/m^3) flows through a horizontal pipe. In the wide section the speed is 3 m/s and the pressure is 200,000 Pa. In the narrow section the speed increases to 5 m/s. Using Bernoulli's equation for horizontal flow, what is the pressure in the narrow section?",
    choices: ["192,000 Pa", "200,000 Pa", "208,000 Pa", "216,000 Pa"], answer: 0,
    explanation: "P2 = P1 + (1/2)rho(v1^2 - v2^2) = 200,000 + 500(9 - 25) = 200,000 - 8,000 = 192,000 Pa." }
];

// Expose for the exam engine (and Node, if ever needed).
if (typeof window !== "undefined") { window.QUESTIONS = QUESTIONS; window.UNITS = UNITS; }
