/* Practice bank (MCQ + FRQ) — content as data. Extracted verbatim from the
   prototype's _practiceData(). Edit questions here without touching app logic. */
export function practiceData() {
    var mcq = [
      { id: 'm1', unit: 1, topic: 'Kinematics', stem: 'A ball is thrown straight up and momentarily stops at the top of its path. At that highest point, what are its velocity and acceleration?', options: ['v = 0 and a = 0', 'v = 0 and a = 9.8 m/s² downward', 'v is maximum and a = 0', 'v = 0 and a = 9.8 m/s² upward'], correct: 1, expl: 'At the apex the velocity is instantaneously zero, but gravity never turns off — the acceleration is \\(g = 9.8\\ \\text{m/s}^2\\) downward for the entire flight. That nonzero acceleration is exactly what reverses the motion.' },
      { id: 'm2', unit: 1, topic: 'Free fall', stem: 'Two balls are released from rest at the same height; one has twice the mass of the other. Neglecting air resistance, which hits the ground first?', options: ['The heavier ball', 'The lighter ball', 'They land at the same time', 'It depends on their sizes'], correct: 2, expl: 'In free fall every object has the same acceleration \\(g\\) regardless of mass, so both fall for the same time and land together. Mass cancels out of \\(\\Delta y = \\tfrac12 g t^2\\).' },
      { id: 'm3', unit: 2, topic: 'Newton\u2019s 2nd law', stem: 'A 2 kg block on a frictionless surface is pushed by a constant net horizontal force of 6 N. What is its acceleration?', options: ['0.33 m/s²', '3 m/s²', '12 m/s²', '6 m/s²'], correct: 1, expl: 'Newton\u2019s second law gives \\(a = \\dfrac{F_{net}}{m} = \\dfrac{6}{2} = 3\\ \\text{m/s}^2\\).' },
      { id: 'm4', unit: 2, topic: 'Circular motion', stem: 'A car rounds a flat circular curve at constant speed. In what direction is the net force on the car?', options: ['Forward, in the direction of motion', 'Toward the center of the curve', 'Outward, away from the center', 'Zero, since the speed is constant'], correct: 1, expl: 'Constant speed does not mean zero acceleration — the direction is changing. The net (centripetal) force points toward the center, supplied here by friction. There is no outward "centrifugal" force on the car.' },
      { id: 'm5', unit: 3, topic: 'Energy conservation', stem: 'A pendulum is released from rest at a height \\(h\\) above its lowest point. Ignoring friction, its speed at the lowest point is:', options: ['\\(gh\\)', '\\(\\sqrt{gh}\\)', '\\(\\sqrt{2gh}\\)', '\\(2gh\\)'], correct: 2, expl: 'Setting \\(mgh = \\tfrac12 mv^2\\) and solving gives \\(v = \\sqrt{2gh}\\). The mass cancels, so the speed is independent of the bob\u2019s mass.' },
      { id: 'm6', unit: 4, topic: 'Collisions', stem: 'Two carts collide and stick together (perfectly inelastic). Which quantity is conserved in the collision?', options: ['Kinetic energy only', 'Momentum only', 'Both momentum and kinetic energy', 'Neither'], correct: 1, expl: 'Momentum is conserved in any collision with no external force. In an inelastic collision kinetic energy is lost to heat, sound and deformation, so it is NOT conserved.' },
      { id: 'm7', unit: 4, topic: 'Impulse', stem: 'A 0.2 kg ball moving at 10 m/s is brought to rest in 0.05 s by a wall. What is the average force the wall exerts?', options: ['2 N', '20 N', '40 N', '100 N'], correct: 2, expl: 'Impulse equals change in momentum: \\(F\\,\\Delta t = \\Delta p\\). So \\(F = \\dfrac{m\\,\\Delta v}{\\Delta t} = \\dfrac{0.2(10)}{0.05} = 40\\ \\text{N}\\).' },
      { id: 'm8', unit: 5, topic: 'Torque', stem: 'To open a heavy door most easily, you should push:', options: ['Near the hinge, perpendicular to the door', 'Far from the hinge, perpendicular to the door', 'Far from the hinge, parallel to the door', 'Anywhere, since only the force matters'], correct: 1, expl: 'Torque is \\(\\tau = rF\\sin\\theta\\). It is maximized by a large lever arm \\(r\\) (far from the hinge) and a perpendicular push (\\(\\theta = 90^\\circ\\), so \\(\\sin\\theta = 1\\)).' },
      { id: 'm9', unit: 6, topic: 'Angular momentum', stem: 'A spinning skater pulls their arms inward, reducing their rotational inertia. With no external torque, what happens?', options: ['Angular velocity increases; angular momentum stays the same', 'Angular momentum increases; angular velocity stays the same', 'Both decrease', 'Both stay exactly the same'], correct: 0, expl: 'With no external torque, angular momentum \\(L = I\\omega\\) is conserved. If \\(I\\) decreases, \\(\\omega\\) must increase to keep \\(L\\) constant. (Rotational KE actually rises — the skater\u2019s muscles do the work.)' },
      { id: 'm10', unit: 7, topic: 'Oscillations', stem: 'A simple pendulum\u2019s period is measured. Which change would increase the period?', options: ['Increasing the mass of the bob', 'Increasing the length of the string', 'Increasing the amplitude (small angles)', 'Moving it to a planet with stronger gravity'], correct: 1, expl: 'Since \\(T = 2\\pi\\sqrt{L/g}\\), only length and gravity matter. A longer string increases \\(T\\); the period is independent of mass and (for small angles) amplitude, and stronger gravity would shorten it.' },
      { id: 'm11', unit: 8, topic: 'Fluids', stem: 'An incompressible fluid flows through a pipe that narrows to half its cross-sectional area. Compared with the wide section, the fluid in the narrow section moves:', options: ['At half the speed', 'At the same speed', 'At twice the speed', 'At four times the speed'], correct: 2, expl: 'The continuity equation \\(A_1 v_1 = A_2 v_2\\) means halving the area doubles the speed. (By Bernoulli, that faster region also has lower pressure.)' },
      { id: 'm12', unit: 8, topic: 'Buoyancy', stem: 'A block floats with 75% of its volume submerged in water (\\(\\rho = 1000\\ \\text{kg/m}^3\\)). What is the density of the block?', options: ['250 kg/m³', '750 kg/m³', '1000 kg/m³', '1333 kg/m³'], correct: 1, expl: 'For a floating object the fraction submerged equals the density ratio: \\(\\dfrac{\\rho_{block}}{\\rho_{water}} = 0.75\\), so \\(\\rho_{block} = 750\\ \\text{kg/m}^3\\).' }
    ];
    var frq = [
      { id: 'f1', num: 1, kind: 'Quantitative/Qualitative Translation', unit: '2\u20133', points: 7, title: 'Block on an incline and rough floor',
        scenario: 'A 2.0 kg block is released from rest at the top of a frictionless ramp inclined at \\(30^\\circ\\), a vertical height of 1.5 m above the floor. At the bottom it slides onto a horizontal floor where the coefficient of kinetic friction is \\(\\mu_k = 0.25\\).',
        parts: [
          { label: 'a', pts: 2, prompt: 'Determine the acceleration of the block while on the frictionless ramp.', lines: [{ pts: '1 pt', text: 'The only force along the ramp is the gravity component \\(mg\\sin\\theta\\), so \\(a = g\\sin\\theta\\).' }, { pts: '1 pt', text: '\\(a = 9.8\\sin 30^\\circ = 4.9\\ \\text{m/s}^2\\), directed down the ramp.' }] },
          { label: 'b', pts: 2, prompt: 'Using energy conservation, determine the speed of the block at the bottom of the ramp.', lines: [{ pts: '1 pt', text: 'Set gravitational PE equal to KE: \\(mgh = \\tfrac12 mv^2\\) (mass cancels).' }, { pts: '1 pt', text: '\\(v = \\sqrt{2gh} = \\sqrt{2(9.8)(1.5)} \\approx 5.4\\ \\text{m/s}\\).' }] },
          { label: 'c', pts: 2, prompt: 'Determine how far the block slides on the rough floor before stopping.', lines: [{ pts: '1 pt', text: 'Friction does negative work equal to the kinetic energy: \\(\\mu_k mg\\, d = \\tfrac12 mv^2\\), so \\(d = \\dfrac{v^2}{2\\mu_k g}\\).' }, { pts: '1 pt', text: '\\(d = \\dfrac{5.4^2}{2(0.25)(9.8)} \\approx 6.0\\ \\text{m}\\).' }] },
          { label: 'd', pts: 1, prompt: 'The experiment is repeated with a 4.0 kg block released from the same height. Is the stopping distance greater, less, or the same? Justify.', lines: [{ pts: '1 pt', text: 'The same. Mass cancels in both \\(v = \\sqrt{2gh}\\) and \\(d = \\dfrac{v^2}{2\\mu_k g}\\), so doubling the mass changes neither the arrival speed nor the stopping distance.' }] }
        ] },
      { id: 'f2', num: 2, kind: 'Experimental Design', unit: '7', points: 7, title: 'Measuring g with a pendulum',
        scenario: 'A student has a set of strings of known lengths, a hanging bob, a meterstick, and a stopwatch. They want to experimentally determine the local acceleration due to gravity, \\(g\\).',
        parts: [
          { label: 'a', pts: 3, prompt: 'Describe an experimental procedure the student could use, including the measurements taken and how to reduce timing error.', lines: [{ pts: '1 pt', text: 'Vary the string length \\(L\\); for each length, measure the period \\(T\\) of small-angle swings.' }, { pts: '1 pt', text: 'Time many oscillations (e.g. 10\u201320) and divide, to reduce reaction-time error in \\(T\\).' }, { pts: '1 pt', text: 'Keep the amplitude small (\\(<15^\\circ\\)) so the simple-pendulum model holds.' }] },
          { label: 'b', pts: 2, prompt: 'Explain how the data should be graphed to produce a straight line, and what should be plotted on each axis.', lines: [{ pts: '1 pt', text: 'From \\(T = 2\\pi\\sqrt{L/g}\\), squaring gives \\(T^2 = \\dfrac{4\\pi^2}{g}L\\) — a line through the origin.' }, { pts: '1 pt', text: 'Plot \\(T^2\\) (y-axis) versus \\(L\\) (x-axis); the graph is linear with slope \\(\\dfrac{4\\pi^2}{g}\\).' }] },
          { label: 'c', pts: 2, prompt: 'Describe how to obtain \\(g\\) from the graph.', lines: [{ pts: '1 pt', text: 'Determine the slope of the best-fit line.' }, { pts: '1 pt', text: 'Solve \\(g = \\dfrac{4\\pi^2}{\\text{slope}}\\). Using the slope (not a single point) averages out random error.' }] }
        ] },
      { id: 'f3', num: 3, kind: 'Quantitative', unit: '4', points: 6, title: 'Collision of two carts',
        scenario: 'On a frictionless track, a 1.5 kg cart moving right at 4.0 m/s collides with a stationary 2.5 kg cart. After the collision the two carts stick together.',
        parts: [
          { label: 'a', pts: 2, prompt: 'Determine the velocity of the combined carts immediately after the collision.', lines: [{ pts: '1 pt', text: 'Conserve momentum: \\(m_1 v_1 = (m_1+m_2)v_f\\).' }, { pts: '1 pt', text: '\\(v_f = \\dfrac{1.5(4.0)}{1.5+2.5} = 1.5\\ \\text{m/s}\\) to the right.' }] },
          { label: 'b', pts: 2, prompt: 'Calculate the kinetic energy lost in the collision.', lines: [{ pts: '1 pt', text: 'Before: \\(KE_i = \\tfrac12(1.5)(4.0)^2 = 12\\ \\text{J}\\). After: \\(KE_f = \\tfrac12(4.0)(1.5)^2 = 4.5\\ \\text{J}\\).' }, { pts: '1 pt', text: '\\(\\Delta KE = 12 - 4.5 = 7.5\\ \\text{J}\\) lost.' }] },
          { label: 'c', pts: 2, prompt: 'Is this collision elastic or inelastic? Justify your answer with a physical principle.', lines: [{ pts: '1 pt', text: 'Inelastic — the kinetic energy decreased (7.5 J was lost).' }, { pts: '1 pt', text: 'Momentum is still conserved (no external horizontal force), but because the carts stick and KE is not conserved, the collision is perfectly inelastic.' }] }
        ] }
    ];
  return { mcq: mcq, frq: frq };
}
